### ISSUE TITLE
Multiple plugs ?

### ISSUE THREAD

**Issue by ShagoY** [rolinux/hs110-exporter#1]
Why indicate "if you have multiple plugs you have to increase the host port number (for example -p 9499:9498 and/or -p 9500:9498)" if you use 1 container per plug ?

I feel like I'm missing something...

**Comment by rolinux** [comment]
If you are using docker and you are mapping the container ports to external network interface you should use 3 different host ports mapped to the same `9498` port for each container.

I use Kubernetes now and the [manifests for plugs](https://github.com/rolinux/k3s-home-manifests/tree/master/monitoring) have the names like `hs110-plug-55`, `hs110-plug-56` and `hs110-plug-57` (from the internal IPs of my plugs).

You also have already made containers images at https://hub.docker.com/r/rolinux/hs110-exporter.

The Golang code should work without containers, compiled and run as a service.

Note: you need the ports for Prometheus to scrape.

**Comment by ShagoY** [comment]
Oh God, I'm an idiot...

You're right, you're right... In fact, I'm looking for a project under docker that allows to manage several plugs in a single container. I focused on it when I asked my question without even thinking.

Sorry about that.
